version: '3.8'

services:
  backtester:
    build:
      context: ..
      dockerfile: ../Dockerfile
    env_file: ../.env
    command: backtester
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - trading-net
    volumes:
      - ../:/app
    restart: "no"

  monte-carlo:
    build:
      context: ..
      dockerfile: ../Dockerfile
    env_file: ../.env
    command: monte-carlo
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - trading-net
    volumes:
      - ../:/app
    restart: "no"
